spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}e86908d7a64f635197b40ffbbee3f46b9d4b8cea297010d400060d5fcdb0973a'

token:  
  expiration_time: 86400000
  secret: user_token_default

gateway:
  ip: 192.168.0.8