spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}9975771f77d82619a0dd9da906b74a800727732ac1d6454b67035d1c981653c1'

token:  
  expiration_time: 86400000
  secret: user_token_default

gateway:
  ip: 192.168.0.8