server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/GitHub/SpringCloud
        git:
          uri: https://github.com/kimmmmsj/SpringCloud
          username: kimmmmsj
          password: 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

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh