server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kimmmmsj/SpringCloud
          username: kimmmmsj
          password: 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