server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kimmmmsj/SpringCloud/tree/main/E-commerce
          username: kimmmmsj
          password: Tjdwo2360$$